// frontend/src/views/Login.vue
<template>
  <div class="min-h-screen bg-slate-50 flex items-center justify-center p-4">
    <div class="bg-white border border-slate-200 rounded-none shadow-xl w-full max-w-md p-10">
      <div class="text-center mb-10">
        <h1 class="text-4xl font-black text-slate-900 mb-2 tracking-tighter uppercase">SOCIMOB</h1>
        <p class="text-slate-600 font-medium">Sistema de Gestão Imobiliária</p>
      </div>

      <form @submit.prevent="handleLogin" class="space-y-6">
        <div>
          <label class="block text-sm font-bold text-slate-900 mb-2 uppercase tracking-wide">
            E-mail
          </label>
          <input
            v-model="email"
            type="email"
            required
            class="w-full px-4 py-3 border-2 border-slate-200 rounded-none focus:ring-0 focus:border-slate-900 transition outline-none font-medium text-slate-900 placeholder-slate-400"
            placeholder="seu@email.com"
          />
        </div>

        <div>
          <label class="block text-sm font-bold text-slate-900 mb-2 uppercase tracking-wide">
            Senha
          </label>
          <input
            v-model="senha"
            type="password"
            required
            class="w-full px-4 py-3 border-2 border-slate-200 rounded-none focus:ring-0 focus:border-slate-900 transition outline-none font-medium text-slate-900 placeholder-slate-400"
            placeholder="••••••••"
          />
        </div>

        <div v-if="error" class="bg-red-50 border-l-4 border-red-500 text-red-700 px-4 py-3 text-sm font-medium">
          {{ error }}
        </div>

        <button
          type="submit"
          :disabled="loading"
          class="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-4 rounded-none transition disabled:opacity-50 disabled:cursor-not-allowed uppercase tracking-widest"
        >
          <span v-if="!loading">Entrar</span>
          <span v-else class="flex items-center justify-center">
            <svg class="animate-spin h-5 w-5 mr-2" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Entrando...
          </span>
        </button>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuth } from '@/composables/useAuth'

console.log('🚀 Login.vue carregado!')

const router = useRouter()
const route = useRoute()
const auth = useAuth()

const email = ref('')
const senha = ref('')
const loading = ref(false)
const error = ref('')

onMounted(() => {
  console.log('✅ Login.vue montado! Componente ativo.')
  console.log('Auth disponível:', !!auth)
})

const handleLogin = async () => {
  console.log('🔐 handleLogin CHAMADO!')
  console.log('Email:', email.value, 'Senha:', senha.value ? '***' : 'vazio')
  
  loading.value = true
  error.value = ''
  
  console.log('🔐 Iniciando login...', { email: email.value })
  
  try {
    const success = await auth.login(email.value, senha.value)
    
    console.log('📥 Resposta do login:', { success, hasError: !!auth.error.value })
    
    if (success) {
      console.log('✅ Login bem-sucedido! Redirecionando...')
      const redirectPath = String(route.query.redirect || '/')
      if (redirectPath.startsWith('/configuracoes')) {
        router.push({ name: 'Settings' })
      } else {
        router.push(redirectPath)
      }
    } else {
      const errorMsg = auth.error.value || 'Erro ao fazer login'
      console.error('❌ Login falhou:', errorMsg)
      error.value = errorMsg
    }
  } catch (err) {
    console.error('💥 Exceção no login:', err)
    error.value = 'Erro ao fazer login. Verifique suas credenciais.'
  }
  
  loading.value = false
}
</script>

// client/src/pages/Login.tsx
import { useState } from 'react';
import { useLocation } from 'wouter';
import { toast } from 'sonner';
import { api } from '@/lib/api';
import { motion } from 'framer-motion';
import { Mail, Lock, Eye, EyeOff, ArrowRight } from 'lucide-react';

export default function Login() {
  const [showPassword, setShowPassword] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [, setLocation] = useLocation();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!email || !password) {
      toast.error('Por favor, preencha todos os campos');
      return;
    }

    setIsLoading(true);

    try {
      const response = await api.post('/auth/login', {
        email,
        password
      });

      if (response.data.token) {
        localStorage.setItem('token', response.data.token);
        localStorage.setItem('user', JSON.stringify(response.data.user));
        toast.success('Login realizado com sucesso!');
        setLocation('/dashboard');
      } else {
        toast.error('Erro ao realizar login: Resposta inválida do servidor');
      }
    } catch (error: any) {
      console.error('Login error:', error);
      const errorMessage = error.response?.data?.message || 'Erro ao realizar login. Verifique suas credenciais.';
      toast.error(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.1, delayChildren: 0.2 },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 },
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-purple-950/20 flex items-center justify-center p-4">
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="w-full max-w-md"
      >
        {/* Logo */}
        <motion.div variants={itemVariants} className="text-center mb-8">
          <motion.div
            initial={{ scale: 0, rotate: -180 }}
            animate={{ scale: 1, rotate: 0 }}
            transition={{ type: 'spring', stiffness: 200 }}
            className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center text-white font-bold text-3xl mx-auto mb-4 glow-lg"
          >
            S
          </motion.div>
          <h1 className="text-3xl font-bold gradient-text mb-2">SOCIMOB</h1>
          <p className="text-muted-foreground">Gestão Imobiliária Inteligente</p>
        </motion.div>

        {/* Login Card */}
        <motion.div
          variants={itemVariants}
          className="glass-panel p-8 rounded-3xl mb-6"
        >
          <h2 className="text-2xl font-bold text-foreground mb-6">Bem-vindo de volta</h2>

          <form onSubmit={handleLogin}>
            {/* Email Input */}
            <motion.div variants={itemVariants} className="mb-6">
              <label className="block text-sm font-semibold text-foreground mb-2">
                Email
              </label>
              <div className="relative">
                <Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" size={20} />
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="seu@email.com"
                  className="w-full pl-12 pr-4 py-3 bg-white/10 border border-white/20 rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                  disabled={isLoading}
                />
              </div>
            </motion.div>

            {/* Password Input */}
            <motion.div variants={itemVariants} className="mb-6">
              <label className="block text-sm font-semibold text-foreground mb-2">
                Senha
              </label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" size={20} />
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  className="w-full pl-12 pr-12 py-3 bg-white/10 border border-white/20 rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                  disabled={isLoading}
                />
                <motion.button
                  type="button"
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                  disabled={isLoading}
                >
                  {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                </motion.button>
              </div>
            </motion.div>

            {/* Remember & Forgot */}
            <motion.div
              variants={itemVariants}
              className="flex items-center justify-between mb-6"
            >
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  className="w-4 h-4 rounded bg-white/10 border border-white/20 cursor-pointer"
                  disabled={isLoading}
                />
                <span className="text-sm text-muted-foreground">Lembrar-me</span>
              </label>
              <a
                href="/forgot-password"
                className="text-sm text-blue-400 hover:text-blue-300 transition-colors"
              >
                Esqueceu a senha?
              </a>
            </motion.div>

            {/* Login Button */}
            <motion.button
              type="submit"
              variants={itemVariants}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              className="w-full flex items-center justify-center gap-2 px-6 py-3 bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 rounded-lg font-semibold text-white transition-all glow-md hover:glow-lg mb-4 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={isLoading}
            >
              {isLoading ? 'Entrando...' : 'Entrar'}
              {!isLoading && <ArrowRight size={20} />}
            </motion.button>
          </form>


        </motion.div>

        {/* Sign Up Link */}
        <motion.div variants={itemVariants} className="text-center">
          <p className="text-muted-foreground">
            Não tem uma conta?{' '}
            <a href="#" className="text-blue-400 hover:text-blue-300 font-semibold transition-colors">
              Crie uma agora
            </a>
          </p>
        </motion.div>

        {/* Footer */}
        <motion.div
          variants={itemVariants}
          className="mt-8 pt-6 border-t border-white/10 text-center text-xs text-muted-foreground"
        >
          <p>© 2026 SOCIMOB. Todos os direitos reservados.</p>
        </motion.div>
      </motion.div>

      {/* Background Decoration */}
      <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
        <div className="absolute top-0 right-0 w-96 h-96 bg-gradient-to-br from-blue-500/10 to-purple-500/10 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-0 w-96 h-96 bg-gradient-to-br from-purple-500/10 to-pink-500/10 rounded-full blur-3xl" />
      </div>
    </div>
  );
}
